### ISSUE TITLE
Policy Execution that returns a strongly typed object

### ISSUE THREAD

**Issue by GenZodd** [App-vNext/Polly.Caching.IDistributedCache#14]
This is a question as I am sure I am missing something. I thought there was a way to execute a caching policy and have it return a strongly typed C# object instead of a string or byte[]. If not I am not sure I am following what the point of the serializer is or the ability to plug in a custom serializer. 

I looked at the sample that gave the below code. The type has to be string or byte[] (as per the check in the code) or you get an error. However that means the Execute method always returns a string or a byte[] which means I am left to deserialize the string to an object via my code. If that is the case why have the `TResult Deserialize(string objectToDeserialize)` method on the `ICacheItemSerializer<TResult, string>` interface? 

It seems I am missing something. 

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddDistributedRedisCache(options =>
        {
            options.Configuration = "localhost"; // or whatever
            options.InstanceName = "SampleInstance";
        });

        services.AddSingleton<Polly.Caching.IAsyncCacheProvider<string>>(serviceProvider => serviceProvider.GetRequiredService<IDistributedCache>().AsAsyncCacheProvider<string>());

        services.AddSingleton<Polly.Registry.IReadOnlyPolicyRegistry<string>, Polly.Registry.PolicyRegistry>((serviceProvider) =>
        {
            PolicyRegistry registry = new PolicyRegistry();
            registry.Add("myCachePolicy", Policy.CacheAsync<string>(serviceProvider.GetRequiredService<IAsyncCacheProvider<string>>(), TimeSpan.FromMinutes(5)));

            return registry;
            });

        // ...
    }

**Comment by reisenberger** [comment]
Hi @GenZodd . We supply `Polly.Caching.Serialization.Json` ([github](https://github.com/App-vNext/Polly.Caching.Serialization.Json); [nuget](https://www.nuget.org/packages/Polly.Caching.Serialization.Json)) as a serializer to serialize any type.  

I've updated the readme of this repo to make that clearer, here: https://github.com/App-vNext/Polly.Caching.IDistributedCache/blob/master/README.md#automatically-serializing-more-complex-type

There is also further information:

+ In the [`Polly.Caching.Serialization.Json` readme](https://github.com/App-vNext/Polly.Caching.Serialization.Json)
+ On the [Polly wiki page about serializers](https://github.com/App-vNext/Polly/wiki/Implementing-cache-serializers)

Let me know if this gives you what you need.

**Comment by GenZodd** [comment]
Thanks, @reisenberger the update to the documentation helps. That is where I landed and got it working but all the string generic types was throwing me off.
