### ISSUE TITLE
Specify the policy to use when the cache is unavailable

### ISSUE THREAD

**Issue by fleed** [App-vNext/Polly.Caching.IDistributedCache#8]
Is it possible to specify a policy to handle the case when the remote cache is not available? E.g. Circuit breaker or similar.

**Comment by reisenberger** [comment]
@fleed If the cache is not available, Polly CachePolicy's behaviour is to [signal the error via the appropriate event hook](https://github.com/App-vNext/Polly/wiki/Cache#interacting-with-policy-operation), then [call the underlying code executed through the policy instead](https://github.com/App-vNext/Polly/wiki/Cache#operation).

_Within_ the Polly.Caching.IDistributedCache implementation, calls to put or get items from the cache ([example](https://github.com/App-vNext/Polly.Caching.IDistributedCache/blob/54bd7a770f9adeb180bbc368ebe0a66f5385f5e0/src/Polly.Caching.Distributed.Shared/NetStandardIDistributedCacheByteArrayProvider.cs#L29)) are not currently policy-guarded.

It would be relatively easy to add a policy there, but it is also common to have [fairly low timeouts (eg 1 second)](https://stackexchange.github.io/StackExchange.Redis/Configuration#configuration-options) to distrib caches ... I guess the gain would be to shorten that timeout from 1 second to 0 second (fail even faster) if a circuit-breaker was indicating the distrib cache was not available - was that your line of thought?

Interested to hear more about your use case - and other community views.

**Comment by reisenberger** [comment]
@fleed / anyone interested: On further thoughts, this should be relatively easy.  It would be possible to define a new `PolicyGuardedAsyncCacheProvider<TResult> : IAsyncCacheProvider<TResult>` which simply wraps calls to an inner `IAsyncCacheProvider<TResult>` in a supplied `IAsyncPolicy`.  Then, configure your original CachePolicy with the new instance of `PolicyGuardedAsyncCacheProvider` in place of the original `IAsyncCacheProvider<TResult>` which you have now wrapped.  

Something like this;

    /// <summary>
    /// A cache provider which wraps calls to another cache provider, with a Polly policy
    /// </summary>
    public class PolicyGuardedAsyncCacheProvider<TResult> : IAsyncCacheProvider<TResult>
    {
        private readonly IAsyncPolicy _policy;
        private readonly IAsyncCacheProvider<TResult> _underlyingCache;

        /// <summary>
        /// Initializes a new instance of the <see cref="PolicyGuardedAsyncCacheProvider "/> class.
        /// </summary>
        /// <param name="policy">The policy to use to guard calls to the underlying cache.</param>
        public PolicyGuardedAsyncCacheProvider(IAsyncCacheProvider<TResult> underlyingCache, IAsyncPolicy policy)
        {
            this._policy = policy ?? throw new ArgumentNullException(nameof(policy));
            this._underlyingCache = underlyingCache ?? throw new ArgumentNullException(nameof(underlyingCache));
        }

        /// <summary>
        /// Gets a value from the underlying cache, guarding the call with the pre-configured Polly policy. 
        /// </summary>
        /// <param name="key">The cache key.</param>
        /// <param name="cancellationToken">The cancellation token.  </param>
        /// <param name="continueOnCapturedContext">Whether async calls should continue on a captured synchronization context. <para><remarks>For <see cref="PolicyGuardedAsyncCacheProvider{TResult}"/>, this parameter is irrelevant and is ignored, as the implementation is synchronous.</remarks></para></param>
        /// <returns>A <see cref="Task{TResult}" /> promising as Result the value from cache; or null, if none was found.</returns>
        public async Task<TResult> GetAsync(string key, CancellationToken cancellationToken, bool continueOnCapturedContext)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return await _policy.ExecuteAsync(ct => _underlyingCache.GetAsync(key, ct, continueOnCapturedContext), cancellationToken, continueOnCapturedContext);
        }

        /// <summary>
        /// Puts the specified value in the cache, guarding the call with the pre-configured Polly policy.
        /// </summary>
        /// <param name="key">The cache key.</param>
        /// <param name="value">The value to put into the cache.</param>
        /// <param name="ttl">The time-to-live for the cache entry.</param>
        /// <param name="cancellationToken">The cancellation token.</param>
        /// <param name="continueOnCapturedContext">Whether async calls should continue on a captured synchronization context. </param>
        /// <returns>A <see cref="Task" /> which completes when the value has been cached.</returns>
        public async Task PutAsync(string key, TResult value, Ttl ttl, CancellationToken cancellationToken, bool continueOnCapturedContext)
        {
            cancellationToken.ThrowIfCancellationRequested();
            await _policy.ExecuteAsync(ct => _underlyingCache.PutAsync(key, value, ttl, ct, continueOnCapturedContext), cancellationToken, continueOnCapturedContext);
        }

Then, you would configure your Polly CachePolicy as 

    IAsyncPolicy cacheGuardPolicy = /* something, eg */ Policy.CircuitBreakerAsync(/* config */);
    IAsyncPolicy<string> guardedRedisCachePolicy = Policy.CacheAsync<string>(new PolicyGuardedAsyncCacheProvider(distributedCache.AsAsyncCacheProvider<string>(), cacheGuardPolicy), TimeSpan.FromMinutes(5));

where `Microsoft.Extensions.Caching.Distributed.IDistributedCache distributedCache`

If anyone wants to put that through its paces, we would be grateful for feedback. My focus at the moment is on other big-ticket Polly features.

If that plays nicely as expected, we could also improve the syntax via an extension method, to make it something like:

    IAsyncPolicy<string> guardedRedisCachePolicy = Policy.CacheAsync<string>(distributedCache.AsAsyncCacheProvider<string>().guardedWith(cacheGuardPolicy)), TimeSpan.FromMinutes(5));

Hope that helps.
